### ISSUE TITLE
Integrate a PID library

### ISSUE THREAD

**Issue by tvanesse** [tvanesse/PVCharacterization#2]
As the device will use a closed loop system to achieve a `(tilt, orientation)` setpoint, we need to integrate a [PID library](http://playground.arduino.cc/Code/PIDLibrary) to control the hemisphere positioning.

**Comment by ahmed-akl** [comment]
ok

**Comment by tvanesse** [comment]
Closing as wontfix since no PID will be used in this project (we use stepper motors).
